# This is a basic workflow to help you get started with Actions

name: Update Changelog

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issuesWoLabels: true
          prWoLabels: true
          author: true
          compareLink: true
          breakingLabel: '**Breaking&nbsp;Changes**'
          enhancementLabel: '**Enhancements**'
          bugsLabel: '**Fixed&nbsp;Bugs**'
          deprecatedLabel: '**Deprecated**'
          removedLabel: '**Removed**'
          securityLabel: '**Security&nbsp;Fixes**'
          issuesLabel: '**Other&nbsp;Changes**'
          prLabel: '**Merged&nbsp;Pull&nbsp;Requests**'

      - name: Push updated changelog
        uses: EndBug/add-and-commit@v7
        with:
          add: CHANGELOG.md
          author_name: Changelog Updater
          author_email: github@illandril.net
          branch: master
          message: Updated changelog
