# When...
# - A commit is tagged with v#.#.#
# This workflow will...
# - Run tests using node
# - Publish a package to GitHub Packages
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish a version

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish-on-tag:
    permissions:
      contents: write
    uses: illandril/FoundryVTT-package-release-action/.github/workflows/illandril-publish.yml@main
    secrets:
      PACKAGE_RELEASE_TOKEN: ${{ secrets.PACKAGE_RELEASE_TOKEN }}
