# When...
# - A commit is pushed to main
# - A pull request is opened
# This workflow will...
# - Run tests using node
# - Run build using node

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    uses: illandril/FoundryVTT-package-release-action/.github/workflows/illandril-validate.yml@main
