name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Substitute the Manifest and Download URLs in the module.json
      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: 'module/module.json'
        env:
          version: ${{github.event.release.name}}
          manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
          download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.zip

      # Create a zip file with all files required by the module to add to the release
      - run: cd module; zip -r ../module.zip *; cd -; zip -r module.zip LICENSE

      # Create a release for this specific version
      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './module/module.json, ./module.zip'
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}

      - name: Update changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issuesWoLabels: true
          prWoLabels: true
          author: true
          compareLink: true
          breakingLabel: '**Breaking&nbsp;Changes**'
          enhancementLabel: '**Enhancements**'
          bugsLabel: '**Fixed&nbsp;Bugs**'
          deprecatedLabel: '**Deprecated**'
          removedLabel: '**Removed**'
          securityLabel: '**Security&nbsp;Fixes**'
          issuesLabel: '**Other&nbsp;Changes**'
          prLabel: '**Merged&nbsp;Pull&nbsp;Requests**'

      - name: Update repo with new version info
        uses: EndBug/add-and-commit@v7
        with:
          add: module/module.json CHANGELOG.md
          author_name: Release Auto-Commit
          author_email: github@illandril.net
          branch: master
          message: Updates version info for ${{github.event.release.name}}
